spring.application.name=app
spring.datasource.url=jdbc:postgresql://ep-spring-frost-a4q7bxbq.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb
spring.datasource.password=npg_wO85IydWKFtg
spring.jpa.hibernate.ddl-auto=update